#1#
CREATE DATABASE IF NOT EXISTS companydb;

#2#
USE companydb;

#3#
CREATE TABLE employee (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) DEFAULT NULL,
    salary INT(11) DEFAULT NULL,
    PRIMARY KEY (id)
)
